sudo: 'required'
language: node_js
node_js:
  - 6
matrix:
  fast_finish: true
cache:
  directories:
    - ~/.npm
    - node_modules
    - "$HOME/google-cloud-sdk/"
# Install services
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_deploy:
  - docker build -f Dockerfile -t david:latest .
  - docker tag david gcr.io/fine-ring-208513/david
  - npm run semantic-release
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - echo $GCLOUD_KEY | base64 --decode > gcloud.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.json
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
