apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: david-frontend-prod
  labels:
    app: david
spec:
  selector:
    matchLabels:
      app: david
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: david
        tier: frontend
    spec:
      containers:
      - name: david
        image: gcr.io/fine-ring-208513/david:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        - name: david_github__token
          valueFrom:
            secretKeyRef:
              name: gh-token
              key: gh_token.txt
        - name: david_site__hostname
          value: http://35.231.39.234
        ports:
        - containerPort: 1337