apiVersion: v1
kind: Service
metadata:
  name: david-frontend-prod
spec:
  selector:
    app: david
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 1337
  type: LoadBalancer
